# Generated by Django 5.0.3 on 2024-05-24 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='owner',
        ),
    ]
